spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
  profiles:
    active: dev,oauth

  data.web.pageable:
    default-page-size: 24 # 페이징 기본 사이즈 24개로 설정
    max-page-size: 99 # 최대 99개까지 페이징 요청 가능

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
