spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true
      hibernate.use_sql_comments: true
  profiles:
    include: local,oauth